LICENSE
README.md
package.json

* Adds package.json license field
* Adds package.json author field
* Adds LICENSE file (Apache 2)
* Adds js tags to README code snippets

chore: Improves package.json, README and adds LICENSE

---

.eslintrc

https://github.com/Talend/tools/blob/master/tools-javascript-formatter/.eslintrc

chore(lint): remove rule

---

package.json

chore(package): update eslint-plugin-jsx-a11y to version 2.2.2

---

src/components/link/AbstractLink.component.jsx
src/components/link/LinkHandle.component.jsx

Removed some useless state handling in linkHandle and little optimisation of calculatePath method

Perf: link and link hand

---

src/actions/link.actions.js
src/actions/link.actions.test.js
src/actions/node.actions.js
src/actions/node.actions.test.js
src/actions/port.actions.js
src/actions/port.actions.test.js
src/components/node/AbstractNode.component.jsx
src/constants/flowdesigner.model.js
src/constants/flowdesigner.proptypes.js
src/reducers/flow.reducer.test.js
src/reducers/link.reducer.js
src/reducers/link.reducer.test.js
src/reducers/node.reducer.js
src/reducers/node.reducer.test.js
src/reducers/port.reducer.js
src/reducers/port.reducer.test.js
src/selectors/portSelectors.js
src/selectors/portSelectors.test.js

Feat: change attr to attributes

---

src/components/FlowDesigner.container.jsx
src/components/__snapshots__/FlowDesigner.container.test.js.snap

remove height so user can set one with css

fix(svg): remove svg heigth

---

src/actions/__snapshots__/link.actions.test.js.snap
src/actions/__snapshots__/node.actions.test.js.snap
src/actions/__snapshots__/port.actions.test.js.snap
src/actions/link.actions.js
src/actions/node.actions.js
src/actions/port.actions.js

add default to element creation

fix(flow): element creation

---

package.json

chores
update everything following the ownership transfert

chores(config): change git url

---

src/selectors/__snapshots__/portSelectors.test.js.snap
src/selectors/portSelectors.js
src/selectors/portSelectors.test.js

port type SINK or SOURCE is now stored in graphicalAttributes

feat(ports): change data structure

---

README.md

update build badge in README.MD

chores: update readme

---

src/actions/__snapshots__/flow.actions.test.js.snap
src/actions/flow.actions.js
src/actions/flow.actions.test.js

fix(zoom): canvas click error

---

package.json
src/components/configuration/NodeType.component.js
src/components/configuration/NodeType.test.js
src/components/node/AbstractNode.component.js
src/components/node/AbstractNode.snapshot.test.js
src/components/node/AbstractNode.test.js
src/components/node/NodesRenderer.test.js
src/components/port/AbstractPort.test.js

fix lint problems
Eslint did not parse all js files under src
Eslint now do parse all js files under src

fix(eslint): eslint run config

---

package.json
src/components/FlowDesigner.container.js
src/components/ZoomHandler.component.js
src/components/configuration/LinkType.component.js
src/components/configuration/NodeType.component.js
src/components/configuration/PortType.component.js
src/components/grid/Grid.component.js
src/components/link/AbstractLink.component.js
src/components/link/LinkHandle.component.js
src/components/link/LinksRenderer.component.js
src/components/node/AbstractNode.component.js
src/components/node/NodesRenderer.component.js
src/components/port/AbstractPort.component.js
src/components/port/PortsRenderer.component.js
src/constants/flowdesigner.proptypes.js
yarn.lock

PropTypes in future will need to be pulled from this peculiar package.

chores(react): use prop-types from package

---

src/actions/node.actions.js
src/components/FlowDesigner.container.js
src/components/grid/Grid.component.js
src/components/grid/__snapshots__/Grid.test.js.snap
src/components/node/AbstractNode.component.js
src/components/node/NodesRenderer.component.js
src/constants/flowdesigner.constants.js
src/reducers/node.reducer.js

The nodes are free of any position constrains. 
Adds snap to grid option that sticks the node to the nearest grid on
drag end.

feat: Adds snap to grid

---

src/constants/flowdesigner.model.js
src/reducers/__snapshots__/flow.reducer.test.js.snap
src/reducers/__snapshots__/link.reducer.test.js.snap
src/reducers/__snapshots__/port.reducer.test.js.snap
src/selectors/__snapshots__/portSelectors.test.js.snap

add a setter for position on the port type

fix(Port): add a position setter

---

src/components/link/LinkHandle.component.js
src/components/link/LinkHandle.test.js

LinkHandle were not consistant with how props were used internaly and produced some warnings hosts apps
fixed proptypes and tests

fix(linkHandle): proptypes and test

---

.travis.yml
package.json
yarn.lock

fix(release):update release script deps and config

---

package.json
yarn.lock

React warn us about missing requestAnimationFrame during test execution
setup jest runner with a proper requestAnimatioFrame polyfill

chores(tests): remove warnings during tests execution

---

src/reducers/__snapshots__/flow.reducer.test.js.snap
src/reducers/flow.reducer.js
src/reducers/flow.reducer.test.js
src/reducers/link.reducer.js
src/reducers/node.reducer.js
src/reducers/port.reducer.js

When you load a Pipeline if something bad happens, we have no log in the console and we have a default pipeline created. So no way to know what happens.
Let the exception be thrown. On all other part lets keep the try catch but log the error

fix(TFD-8863): do not empty try catch

---

.travis.yml
package.json
yarn.lock

This PRs aims to lower the number of CVE.
They comes from dev deps, so we don't need to publish the package and upgrade it in streams.
Nonetheless I have take the opportunity to upgrade several deps with patch or minor versions.
I will try to do another PR with major upgrades to "revive" this repo.
https://jira.talendforge.org/browse/TFD-10827
We have some vulnerabilities
Upgrade talend script and get rid of theses vulnerabilities
If this PR contains a breaking change, …

fix(TFD-10827): Fix CVE

---

jenkins/veracode-scan.groovy

**What is the problem this PR is trying to solve?**
**What is the chosen solution to this problem?**
-   [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)
-   [ ] Related design / discussions / pages, if any, are all linked or available in the PR
**[ ] This PR introduces a breaking change**

chore(TFD-10837): add srcclr scans to TPD jenkins

---

package.json
yarn.lock

**What is the problem this PR is trying to solve?**
security issues reported
**What is the chosen solution to this problem?**
yarn upgrade.
OK => not found after ui-scripts update
OK => Found "lodash@4.17.21"
OK: not found after upgrade
OK => Found "webpack#ssri@6.0.2"
OK => Found "copy-webpack-plugin#ssri@8.0.1"
-   [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)
-   [ ] Related design / discussions / pages, if any, are all linked or available in the PR
**[ ] This PR introduces a breaking …

chore(TFD-12974): upgrade

---

.github/workflows/autopublish.yml
.github/workflows/ci.yml
.github/workflows/update-yarn-talend.yml
yarn.lock

**What is the problem this PR is trying to solve?**
security issue with path-parse
**What is the chosen solution to this problem?**
yarn upgrade
so path-parse is now 1.0.7
https://github.com/Talend/react-flow-designer/pull/294/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deL8690
-   [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)
-   [ ] Related design / discussions / pages, if any, are all linked or available in the PR
**[ ] This PR introduces a breaking change**

chore: upgrade deps
